### ISSUE TITLE
Is it possible to add multikey binding?

### ISSUE THREAD

**Issue by nohwnd** [martin-stone/touchcursor#1]
First of all, thanks for your tool. I've been using it for quite a while and frankly can't imagine my work day without it. It helped me from wrist pains almost completely and saves me a ton of hand movements every day I am coding with it.

Now to my question. I am trying to replace some of the functionality that is hard to reach from normal typing position. One of those shortcuts is Alt+Shift+Tab (go through opened windows in backwards direction). Is that possible with the current version of Touch Cursor? If not, is there a technical limitation why not?

**Comment by martin-stone** [comment]
Looks like there are certainly issues with doing this on Windows 8:

https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/4b6dbc43-a026-4957-9178-91d2001e2d0d/windows-8-block-alttab-simulation?forum=windowsaccessibilityandautomation

What OS are you using?

**Comment by nohwnd** [comment]
At this point I am running on Windows 7 at work and on Windows 10 at home. I did not try the binding on Windows 10 yet. I will test that when I get home and see if that works.

**Comment by martin-stone** [comment]
Similarly, I'm Win7 at work and Win8.1 at home. On Win7 I can get it to switch windows, but it doesn't keep the available-windows display up between keypresses if I bind the full Alt+Shift+Tab. 

However, if I bind Shift+Tab to {some-key}, and then hold Alt+Space+{some-key}, it works properly, and keeps the available-windows display up until I release Alt. I'll try this on Win8 when I get home.

Apart from any Win8+ problems, the code would need changing to introduce "hold down modifier keys until space released" behaviour. I'm not sure how feasible this is yet. Maybe having the Alt key not bound is the solution in the meantime.

**Comment by martin-stone** [comment]
Confirmed: Just binding Shift+Tab doesn't help on Win8. Looks like manifest tweaks (at minimum) would be necessary.

**Comment by nohwnd** [comment]
Thanks for the info. The Alt-controls-the-list-of-opened-windows behaviour is something I also noticed, but didn't want to go into details.

Thanks for the trick with `Shift+Tab`, but it won't help me much, because the whole point of this was to avoid pressing Alt altogether, as it forces me to move my hand from the home row. 

Consider my problem solved :+1:
