### ISSUE TITLE
Run parallel instances

### ISSUE THREAD

**Issue by tejasvi** [martin-stone/touchcursor#15]
<details>
<summary>I wanted to use modifiers apart from space.</summary>
Using <kbd>f, j</kbd> as Ctrl, <kbd>d, k</kbd> as Shift, <kbd>a, l</kbd> as Alt.
</details> It should be possible by running multiple instances of Touchcursor parallelly. Is it feasible? After combing through issues, I found #7 can be solved using this mechanism.

**Comment by tejasvi** [comment]
I managed to get multiple instances work in parallel by killing mutant for every Touchcursor process in Process explorer. Everything is working as flawless as expected except for one minor hitch. I am unable to use key bindings involving modifier keys used by other instances.

BTW, this code prevents multiple instances. Since project is a bit dated, not sure it can be rebuilt without much fiddling.
https://github.com/martin-stone/touchcursor/blob/77fd76e47e8c07ea8362ca256707c3d2ec728ce8/tclib/win32funcs.cpp#L66-L69

**Comment by martin-stone** [comment]
> Since project is a bit dated, not sure it can be rebuilt without much fiddling.

I understand this sentiment, but apparently it's [straightforward to build with latest tools](https://github.com/martin-stone/touchcursor/issues/14#issuecomment-739336170).

**Comment by tejasvi** [comment]
tcconfig requires wxwidgets v2.8, whose official dlls are incompatible with VS2019 and is a chore to build. Anyway, rebuilding touchcursor is all I needed, and it worked out of the box.
