### ISSUE TITLE
Whitelist edit did not work proper when the global utf-8 support was enabled in Win10

### ISSUE THREAD

**Issue by rzhb** [martin-stone/touchcursor#16]
"Beta: Use Unicode UTF-8 for worldwide language support" is useful for some programmers on a non-english Win10.
The setting can be found here: Settings -> Time & Language -> Language -> "Administrative Language Settings"

![](https://i.stack.imgur.com/dv0tU.png)

When this setting is checked, the "edit program list" in TouchCursor only can got garbled character or blank.

**Comment by martin-stone** [comment]
Actually this happens for me when it's unchecked too. Possibly needs a rebuild with the latest sdk.
