### ISSUE TITLE
Trying to backup settings. Which file to save?

### ISSUE THREAD

**Issue by Caedendi** [martin-stone/touchcursor#17]
Hi,

I want to backup my TouchCursor settings (key binds) so I can quickly set it up on a new device.

Which file stores the settings?

Thx in advance!

**Comment by bubbavox** [comment]
I've never actually tried restoring a backup, but on my machine it's `settings.cfg` in `C:\Users\bubba\AppData\Roaming\TouchCursor` -- unless I'm mistaken.

**Comment by Caedendi** [comment]
Just confirmed this: the `settings.cfg` file mentioned in the location above is indeed where key bind settings are stored and can be backed up.

Thx for the quick response, I'ma close this now.
