### ISSUE TITLE
Combinations with Windows key not working (Windows 10)

### ISSUE THREAD

**Issue by FSund** [martin-stone/touchcursor#5]
First of all, thank you very much for a very nice program.

I have but one issue. If I press Win+Space+L (to move a window to the right of the screen in Windows), Windows 10 will lock the screen, even if Space is kept pressed. This is not a huge issue, but somewhat annoying, as I often use use Win+Arrow Keys to move windows around.

The shortcut for locking the screen is Win+L.

I would rather not change the hotkey for locking the screen, so perhaps you could see if there is a solution to this.

**Comment by martin-stone** [comment]
I would expect Win+L to be handled at a low level before TouchCursor gets a chance to interfere. Otherwise one could write some malware that throws up a fake lock screen and harvests passwords. So unfortunately, I don't think this can be solved.

**Comment by FSund** [comment]
I think you might be correct. 

Looking at [this Stackoverflow](http://stackoverflow.com/a/317550/1850917) post and the comments it seems like this was possible on Windows XP, but not on newer Windows versions.

**Comment by RamonkHarrison** [comment]
The key didn't work for me. Guys you can get working keys for windows 10 from
 www.Windows10KeySale.com
I got a new one from there.
