### ISSUE TITLE
Execute a program or System Task on command line

### ISSUE THREAD

**Issue by prassanakalyan** [martin-stone/touchcursor#9]
Is it possible to run a program or a system command on Windows 10 when a combination is pressed? This would help a lot.
There can be a link to a file/command that a user may want to run when a combination is pressed.
For instance: **%windir%\system32\SnippingTool.exe /clip** can be assigned to Space+S to activate Snipping tool directly without having to click through the start menu.
Note that I am invoking the tool with arguments.

**Comment by martin-stone** [comment]
You can set up a hotkey for your command with (e.g.) [AutoHotkey](https://autohotkey.com/), and then get TouchCursor to trigger it. You'll be able to use a key combo that's obscure and won't clash with anything else, e.g. Ctrl+Alt+Shift+F13. You'll also have all of AutoHotkey's power available.
